### ISSUE TITLE
[es/snapshot.create] Missing [X-Elastic-Product] header

### ISSUE THREAD

**Issue by jloisel** [elastic/elasticsearch-java#74]
**Elasticsearch version** (`bin/elasticsearch --version`): `7.16.2`

**Plugins installed**: []

**JVM version** (`java -version`): 

```
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.21.10)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.21.10, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system): 
> Linux pop-os 5.15.8-76051508-generic #202112141040~1639505278~21.10~0ede46a SMP Tue Dec 14 22:38:29 U x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

When performing a snapshot using the new Java client, it fails due to missing `X-Elastic-Product` header sent by Elasticsearch.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Create an FS repository,
 2. Create a snapshot using the new java client:

```java
final CreateSnapshotRequest request = new CreateSnapshotRequest
  .Builder()
  .repository(repository)
  .snapshot(name)
  .waitForCompletion(waitForCompletion)
  .build();
client.create(request);
```

Client being used (maven dep):

```xml
<elasticsearch.version>7.16.2</elasticsearch.version>

...

      <dependency>
        <groupId>co.elastic.clients</groupId>
        <artifactId>elasticsearch-java</artifactId>
        <version>${elasticsearch.version}</version>
      </dependency>
```

 3. The code throws an exception.

**Provide logs (if relevant)**:

```
co.elastic.clients.transport.TransportException: [es/snapshot.create] Missing [X-Elastic-Product] header. Please check that you are connecting to an Elasticsearch instance, and that any networking filters are preserving that header.

	at co.elastic.clients.transport.rest_client.RestClientTransport.checkProductHeader(RestClientTransport.java:340)
	at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:250)
	at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:144)
	at co.elastic.clients.elasticsearch.snapshot.ElasticsearchSnapshotClient.create(ElasticsearchSnapshotClient.java:142)
```

**Comment by dakrone** [comment]
I've transferred this to the elasticsearch-java repo, since this mentions using the new Java client rather than the old HLRC.

**Comment by swallez** [comment]
@jloisel can you check that the `X-Elastic-Product` HTTP header is effectively received by the machine running your application? Is there an intermediate proxy between your application and the Elasticsearch server that would filter out this header?

**Comment by jloisel** [comment]
Hi,

Elasticsearch is running on my local machine (docker container). The response doesn't contain the `X-Elastic-Product` header when debugging the java sdk. There is no proxy / no intermediate. Everything runs on my local computer.

**Comment by swallez** [comment]
@jloisel can you provide us the command line used to start the Docker container, so that we can try to reproduce the issue?

**Comment by jloisel** [comment]
Here is the `docker-compose.yml` I use:

```yml
version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    stdin_open: true
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    tty: true
    environment:      
      - path.repo=/tmp
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200/tcp
      - 9300:9300/tcp
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    stdin_open: true
    tty: true
    ports:
      - 5601:5601/tcp
    restart: always

volumes:
  elasticsearch-data:
    driver: local
  postgres-data:
    driver: local
```
